name: deploy-astro
# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch
env:
  ## Set API Token as an environment variable
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.10.1
      with:
        deployment-id: cmn7dlgks2ft201p9877j46fj
        parse: true
